name: Secrets example
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      env: 
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run lint
    - run: npm run test 
    env: 
      MONGODB_URI: ${{ secrets.MONGODB_URI }}



  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          if [ "$MONGODB_URI" == "candy" ]
          then
            echo "Got secret"
          fi
          if [ "$PEAR_SECURE" == "pear" ]
          then
            echo "Got secret something else"
          fi
        env: 
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          PEAR_SECURE: ${{ secrets.PEAR_MAGIC_SECURE }}
